DROP TABLE GameUsers CASCADE CONSTRAINTS;

DROP TABLE Friends CASCADE CONSTRAINTS;

DROP TABLE PlayersStatistics CASCADE CONSTRAINTS;

DROP TABLE Inventories CASCADE CONSTRAINTS;

DROP TABLE Items CASCADE CONSTRAINTS;

DROP TABLE Guilds CASCADE CONSTRAINTS;

DROP TABLE Players CASCADE CONSTRAINTS;

DROP TABLE Questions CASCADE CONSTRAINTS;

DROP TABLE Rounds CASCADE CONSTRAINTS;

DROP TABLE BattlesHistory CASCADE CONSTRAINTS;
/

CREATE TABLE Rounds (
	 roundID INT NOT NULL PRIMARY KEY
	,NAME VARCHAR2(100) NOT NULL
	,course VARCHAR2(4000) NOT NULL
	)
/

CREATE TABLE Questions (
	 questionID INT NOT NULL PRIMARY KEY
	,question VARCHAR2(2000) NOT NULL
    ,difficulty VARCHAR2(10) DEFAULT 'medium' NOT NULL
	,answerA VARCHAR2(2000) NOT NULL
	,answerB VARCHAR2(2000) NOT NULL
	,answerC VARCHAR2(2000) NOT NULL
	,answerD VARCHAR2(2000) NOT NULL
	,correctAnswer INT NOT NULL
	,roundID INT NOT NULL
	,FOREIGN KEY (roundID) REFERENCES Rounds(roundID)
	)
/ 
  ALTER TABLE Questions ADD CONSTRAINT CK_CORRECT_ANSWER CHECK
  (
    1 <= CORRECTANSWER
    AND
    4 >= CORRECTANSWER
  )
  ENABLE;
  
  ALTER TABLE Questions ADD CONSTRAINT CK_DIFFICULTY CHECK
  (
    DIFFICULTY IN('easy','medium','hard')
  )
  ENABLE;
/

CREATE TABLE Guilds (
	 guildID INT NOT NULL PRIMARY KEY
	,NAME VARCHAR2(100) NOT NULL
	,description VARCHAR2(1000)
	,wins INT DEFAULT 0 NOT NULL
	,loses INT DEFAULT 0 NOT NULL
	)
/
  ALTER TABLE Guilds ADD CONSTRAINT CK_WINS_POSITIVITY CHECK
  (
    WINS >= 0
  )
  ENABLE;
  
  ALTER TABLE Guilds ADD CONSTRAINT CK_LOSES_POSITIVITY CHECK
  (
    LOSES >= 0
  )
  ENABLE;
/

CREATE TABLE Players (
	 playerID INT NOT NULL PRIMARY KEY
	,playerName VARCHAR2(100) NOT NULL
	,photoURL VARCHAR2(1000) DEFAULT 'defaultPlayer.png' NOT NULL
	,experience INT DEFAULT 0 NOT NULL
	,playerLevel INT DEFAULT 0 NOT NULL
	,cookies INT DEFAULT 0 NOT NULL
	,s_luck INT DEFAULT 0 NOT NULL
	,s_time INT DEFAULT 0 NOT NULL
	,s_cheat INT DEFAULT 0 NOT NULL
    ,skillPoints INT DEFAULT 0 NOT NULL
	,lastRoundID INT REFERENCES Rounds(roundID)
	,guildID INT REFERENCES Guilds(guildID)
	)
/
  ALTER TABLE Players ADD CONSTRAINT CK_SKILLPOINTS_AVAILABLE CHECK
  (
    SKILLPOINTS >= 0
  )
  ENABLE;
  
  ALTER TABLE Players ADD CONSTRAINT CK_EXPERIENCE_POSITIVITY CHECK
  (
    EXPERIENCE >= 0
  )
  ENABLE;
  
  ALTER TABLE Players  ADD CONSTRAINT CK_PLAYER_LEVEL_POSITIVITY CHECK
  (
    PLAYERLEVEL >= 0
  )
  ENABLE;
  
  ALTER TABLE Players  ADD CONSTRAINT CK_COOCKIES_POSITIVITY CHECK
  (
    COOKIES >= 0
  )
  ENABLE;
 
  ALTER TABLE Players  ADD CONSTRAINT CK_S_LUCK_POSITIVITY CHECK
  (
    S_LUCK >= 0
  )
  ENABLE;
  
  ALTER TABLE Players  ADD CONSTRAINT CK_S_TIME_POSITIVITY CHECK
  (
    S_TIME >= 0
  )
  ENABLE;
  
  ALTER TABLE Players  ADD CONSTRAINT CK_S_CHEAT_POSITIVITY CHECK
  (
    S_CHEAT >= 0
  )
  ENABLE;
/

CREATE TABLE GameUsers (
	 playerID INT NOT NULL PRIMARY KEY
	,username VARCHAR2(100) NOT NULL
	,email VARCHAR2(100) NOT NULL
	,password VARCHAR2(100) NOT NULL
	,facebookID VARCHAR2(1000)
	,registrationDate DATE DEFAULT SYSDATE NOT NULL
	,FOREIGN KEY (playerID) REFERENCES Players(playerID)
	)
/

CREATE TABLE Friends (
	 player1ID INT NOT NULL
	,player2ID INT NOT NULL
	,PRIMARY KEY (
		player1ID
		,player2ID
		)
	,FOREIGN KEY (player1ID) REFERENCES Players(playerID)
	,FOREIGN KEY (player2ID) REFERENCES Players(playerID)
	)
/

CREATE TABLE PlayersStatistics (
	 playerID INT NOT NULL PRIMARY KEY
	,wins INT DEFAULT 0 NOT NULL
	,loses INT DEFAULT 0 NOT NULL
	,perfectRounds INT DEFAULT 0 NOT NULL
	,dailyLogins INT DEFAULT 1 NOT NULL
	,lastLoginDate DATE DEFAULT SYSDATE NOT NULL
	,FOREIGN KEY (playerID) REFERENCES Players(playerID)
	)
/ 
  ALTER TABLE PlayersStatistics  ADD CONSTRAINT CK_STATISTIC_WINS_POSITIVITY CHECK
  (
    WINS >= 0
  )
  ENABLE;
  
  ALTER TABLE PlayersStatistics  ADD CONSTRAINT CK_STATISTIC_LOSES_POSITIVITY CHECK
  (
    LOSES >= 0
  )
  ENABLE;
  
  ALTER TABLE PlayersStatistics  ADD CONSTRAINT CK_DAILYLOGINS_POSITIVITY CHECK
  (
    DAILYLOGINS >= 0
  )
  ENABLE;
/

CREATE TABLE Items (
	 itemID INT NOT NULL PRIMARY KEY
	,name VARCHAR2(1000) NOT NULL
	,description VARCHAR2(2000) NOT NULL
	,skillPoints INT -- can be null when the item represents course notes
	,skill VARCHAR2(100) -- same
	,cookiesCost INT NOT NULL
	,filePath VARCHAR2(2000) DEFAULT 'item.png' NOT NULL
	)
/
  ALTER TABLE Items ADD CONSTRAINT CK_SKILLPOINTS_POSITIVITY CHECK
  (
    SKILLPOINTS >= 0
  )
  ENABLE;
  
  ALTER TABLE Items ADD CONSTRAINT CK_SKILL_TYPE CHECK
  (
    SKILL IN ('S_LUCK','S_TIME', 'S_CHEAT') 
  )
  ENABLE;
  
  ALTER TABLE Items ADD CONSTRAINT CK_COOKIESCOST_POSITIVITY CHECK
  (
    COOKIESCOST >= 0
  )
  ENABLE;
/

CREATE TABLE Inventories (
	 playerID INT NOT NULL
	,itemID INT NOT NULL
	,PRIMARY KEY (
		playerID
		,itemID
		)
	,FOREIGN KEY (playerID) REFERENCES Players(playerID)
	,FOREIGN KEY (itemID) REFERENCES Items(itemID)
	)
/

CREATE TABLE BattlesHistory
(
   battleID INT NOT NULL PRIMARY KEY
  ,player1ID INT NOT NULL REFERENCES Players(playerID)
  ,player2id INT NOT NULL REFERENCES Players(playerID)
  ,winner INT
)
/
  ALTER TABLE BattlesHistory ADD CONSTRAINT CK_VALID_WINNER CHECK
  (
    WINNER IN (0,1,2)
  )
  ENABLE;